name: fenicsx-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - fenics-dolfinx=0.6.0
  - numpy=1.26
  - scipy=1.10
  - matplotlib=3.7
  - pandas=2.3
  - scikit-learn=1.2
  - setuptools=78.1
  - h5py=3.13
  - mpi4py=3.1
  - pyvista=0.45
  - arviz=0.15
  - pip=25
  - seaborn=0.13
  - pytest=8.4
  - python-gmsh=4.12
  - pvlib-python=0.13
  - jsonschema=4.24
  - meshio
  - pint
  - pyproj
  - tqdm
  - git

  - pip:
      - git+https://github.com/BAMresearch/FenicsXConcrete@my-grf
      - git+https://github.com/BAMresearch/probeye
      - chaospy==3.3.9
      - doit==0.36.0
      - jinja2==3.1.6
      - pdf2image==1.17.0